### ISSUE TITLE
Bad head merge

### ISSUE THREAD

**Issue by darkknightik** [ultraq/thymeleaf-layout-dialect#69] opened 2015-04-15 21:03 UTC
HI, i have tried your dialect and i like it, but i have one problem. 
Layout file:
http://pastebin.com/ZCR2jNQT

Content file:
http://pastebin.com/BWDm2eHQ

And resolution html:
http://pastebin.com/dZ7NZu4F

Where is problem?

Configuration of Thymeleaf is here:
http://pastebin.com/847c84Vp

Thanks!

**Comment by ultraq** [comment] 2015-04-19 23:59
Hi there, is the problem the duplicating of all the entries?  If so, then this is the expected behaviour: when the `<head>` section is merged, it copies all of the stuff in the content file, into the decorator.  Because you've listed the meta tags, stylesheets, and scripts in both the layout and content files, you end up with doubles.  To fix that, then just mention the meta/stylesheet/script in one of the files.  If you expect to use them in all pages that use the layout, then keep them in the layout and remove them from the content file.

There is a special case when merging the `<title>` element, which is mentioned in the readme and is to do with controller title patterns.

**Comment by cenggel** [comment] 2015-08-05 03:54
Is it possible to add exclude attribute to the head element to exclude merge to layout head.  Because in order to static prototyping templates css need to include all template pages.

**Comment by ultraq** [comment] 2015-08-08 10:44
Hmm, I'll have to think about a way to do that.  I'll open a new issue to ponder that, figure out how it might be done if at all.

**Closed by ultraq** 2015-08-08 10:44 UTC
Labels: question

**Comment by ultraq** [comment] 2015-08-30 00:35
@cenggel I'm not sure if I'll implement something like that, but there is already something in Thymeleaf that can help you there: use `th:remove="all"` or `th:remove="tag"` on those elements you don't want merged so that they're not there in the final result.
