### ISSUE TITLE
ArrayIndexOutOfBoundsException in IModelExtensions.calculateModelSize

### ISSUE THREAD

**Issue by tobiasflohre** [ultraq/thymeleaf-layout-dialect#143] opened 2016-11-07 14:02 UTC
Hi,

when updating to 2.1.0 we got this Exception in processing a formerly working template:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 289
	at org.thymeleaf.engine.Model.get(Model.java:136)
	at org.thymeleaf.model.IModel$get.call(Unknown Source)
	at nz.net.ultraq.thymeleaf.models.extensions.IModelExtensions.calculateModelSize(IModelExtensions.groovy:425)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at nz.net.ultraq.thymeleaf.models.extensions.IModelExtensions$_apply_closure1$_closure22.doCall(IModelExtensions.groovy:359)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:84)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nz.net.ultraq.thymeleaf.models.extensions.IModelExtensions$_apply_closure1$_closure24.doCall(IModelExtensions.groovy:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:84)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at nz.net.ultraq.thymeleaf.decorators.DecorateProcessor.doProcess(DecorateProcessor.groovy:107)
	at org.thymeleaf.processor.element.AbstractAttributeModelProcessor.doProcess(AbstractAttributeModelProcessor.java:76)
	... 87 more
```

There was an unclosed p tag, we closed it, and the Exception was gone, but p tags don't need to be closed. Just wanted to let you know...

**Comment by ultraq** [comment] 2016-11-07 17:28
Thanks for giving 2.1.0 a go and letting me know about this.  I know exactly what the problem is after talking w/ Daniel and raising #142.  I should have a fix for you shortly.

**Comment by ultraq** [comment] 2016-11-07 18:56
`2.1.1-SNAPSHOT` uploaded with a fix for this bug.  Could you please give it a try @tobiasflohre and let me know if it works for you?

**Comment by ultraq** [comment] 2016-11-10 05:39
Hi @tobiasflohre, I'm going to go ahead and release this as 2.1.1 within the next day - I think the test I have covers a lot of the scenarios mentioned by Daniel in #142, and your non-closed `<p>` tag as well.

**Comment by tobiasflohre** [comment] 2016-11-10 07:11
Okay, sorry, I didn't have the time to test it, and I won't have it this week. So go ahead!

**Closed** 2016-11-10 07:14 UTC
Labels: bug
